export const baseURL = "https://api.partner.gce1.bestmile.io",
  userID = "USER_ID",
  iOS_userID = "iOS_USER_ID",
  android_userID = "ANDROID_USER_ID",
  siteID = "SITE_ID",
  apiKey = "BESTMILE-API-KEY",
  domainID = DOMAIN_ID,
  mapsURL = "https://maps.googleapis.com/maps/api/geocode/json?",
  mapsAPIKey = "GOOGLE-MAPS-API-KEY";
